version: "3.8"
services:
  database:
    image : mongo
    container_name: database
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /leanbot/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped